### ISSUE TITLE
Setting up termux 

### ISSUE THREAD

**Issue by chibsah1988** [UndeadSec/SocialFishMobile#11]
Please I just bought a new phone I downloaded termux I want to set it up I need help

**Comment by CodedX-cyber** [comment]
apt-get update && upgrade
pkg install git
pkg install python
pkg install python3
pkg install pip
pip install -r requirements.txt

**Comment by chibsah1988** [comment]
Am done boss I want to be able to hack facebook with zphisher I had it on
my other phone but this is new one am finding it difficult guide me all the
that is installed I need next step
